"""Week 1 only: authored study cards, application prompts and indicative marking points."""
DATA={}
def add(g,subject,title,codes,page,activity,safety,raw):
    cards=[]
    for line in raw.strip().splitlines():
        v=line.split('|');assert len(v)==6,(title,line)
        answer,definition,application,wrong,reason,extend=v
        cards.append(dict(answer=answer,fact=definition,q1='Which term best matches this description: '+definition[0].lower()+definition[1:]+'?',q2=application,wrong=wrong.split(';'),reason=reason,extend=extend))
    assert len(cards)==10 and all(len(c['wrong'])==3 for c in cards)
    DATA[(g,subject)]=dict(title=title,codes=codes,page=page,activity=activity,safety=safety,cards=cards)

add(4,'Science','Classifying insects, birds, mammals and reptiles','B4.1.1.1.1',24,'Sort photographs of an ant, butterfly, hen, bat, goat, snake and lizard. Justify each group by body features, not habitat alone. Include a fish as an example outside the four target groups. Draw and label one representative of each target group.','Use pictures; do not handle unknown animals, reptiles or stinging insects.', '''Insect|An animal in a group whose adults have six legs and three main body regions|An adult animal has six legs, antennae, a head, thorax and abdomen. Which group fits it?|Bird;Mammal;Reptile|Adult ants and butterflies have six legs attached to the thorax. Wings alone are unreliable because not all insects have them and birds also have wings.|Explain why legs and body regions are better evidence than wings alone when identifying an adult insect.
Bird|An animal belonging to the group characterised by feathers|A hen cannot fly far but has feathers. In which group should it be classified?|Insect;Mammal;Reptile|Feathers identify the group. Flight is not essential: hens and ostriches are birds even though their flight abilities differ.|Explain why an ostrich remains in this group even though it cannot fly.
Mammal|An animal in a group with hair at some life stage and milk production by females for their young|A bat flies but has hair and feeds its young milk. Which group includes it?|Bird;Insect;Reptile|Hair and feeding young with milk support classification as a mammal. Movement alone does not determine the group.|Explain how a bat and a goat can belong to the same group despite moving differently.
Reptile|An animal in a group generally characterised by dry scaly skin and breathing through lungs|An animal has dry scales, breathes with lungs and crawls on land. Which target group best fits it?|Insect;Bird;Mammal|Snakes and lizards share these features. Snakes lack legs, so legs cannot be required for the group; fish scales also show why multiple features matter.|Explain why lacking legs does not prevent a snake from belonging to this group.
Thorax|The middle of the three main body regions of an insect, carrying its legs|Which insect body region should connect to all six legs in a butterfly drawing?|Head;Abdomen;Tail|The thorax lies between the head and abdomen. Legs and, when present, wings attach there.|Describe the location of this region and state what attaches to it.
Antennae|Paired sensory structures on an insect’s head|An ant touches objects with two slender structures on its head. What are these?|Feathers;Hooves;Scales|These structures detect environmental information such as touch and chemicals. They are not extra walking legs.|Explain why an insect with two of these structures still has six legs.
Feathers|The distinctive body covering of birds, helping insulation and in many birds flight|A duck and a hen share which distinctive body covering?|Hair;Dry reptile scales;Insect shell|Both have feathers despite different habits. Covering is useful classification evidence whereas habitat alone is not.|Explain how this covering supports grouping a hen and a duck together.
Hair|A characteristic mammalian covering that may be dense or sparse|Which covering on a goat helps distinguish it from a hen?|Feathers;Fish scales;Insect wings|Goats have hair and females feed young with milk. Using more than one feature makes the classification stronger.|Give two features that support classifying a goat as a mammal.
Backbone|An internal supporting structure shared by vertebrates|A hen, goat and lizard share which structure that an insect lacks?|Antennae;Six legs;Feathers|Birds, mammals and reptiles have backbones. Insects have an external supporting covering and no backbone.|Explain how this structure separates an insect from a bird without referring to wings.
Classification|Grouping organisms according to shared features|Pupils group animal cards using covering, leg number and feeding of young. What process are they using?|Germination;Evaporation;Condensation|Good grouping uses consistent evidence about shared features. Colour, fear or whether an animal is liked is less useful for these biological groups.|Explain why grouping only by colour is less useful than grouping by body structure.''')

add(5,'Science','Growth, sensitivity, respiration and excretion','B5.1.1.1.1',26,'Record a seedling’s height and leaf number on several dates. Make a four-column table for growth, sensitivity, respiration and excretion. Separate what can be directly observed from what is explained using biological knowledge.','Use safe observation. No tasting unknown substances, prolonged breath-holding or contact with hot objects.', '''Growth|A lasting increase in an organism’s size and usually its dry mass|A seedling becomes taller and develops more leaves over two weeks. Which life process is shown?|Excretion;Respiration;Sensitivity|Repeated measurements of the same plant support the conclusion. A brief change in water content alone is not enough to demonstrate lasting growth.|Describe how you would collect evidence that a seedling is growing.
Sensitivity|The ability to detect and respond to changes in the surroundings|A person withdraws a hand from an uncomfortably hot surface. Which life process is shown?|Growth;Excretion;Reproduction|Heat is the stimulus and withdrawing the hand is the response. The response protects the person from injury.|Identify the stimulus and response and explain the benefit of the response.
Respiration|Chemical processes in cells that release usable energy from food|Muscle cells release energy from food while a child runs. Which process is involved?|Growth;Excretion;Pollination|Cells require energy for movement, growth and repair, even when the person is not visibly active. Respiration is not simply moving air in and out.|Explain why a sleeping person still needs this process.
Excretion|Removal of waste products made by the body’s chemical processes|The lungs remove carbon dioxide produced by cells. Which life process is this?|Germination;Nutrition;Reproduction|Carbon dioxide is a metabolic waste produced during aerobic respiration. Removing it is excretion, unlike removing undigested food by egestion.|Explain why carbon-dioxide removal counts as this process.
Stimulus|A detectable change that can trigger a response|Bright light causes a person to narrow their eyes. What role does the bright light play?|Response;Nutrient;Excretory organ|The light is the change detected. Narrowing the eyes is the response, not the stimulus.|Distinguish the stimulus from the response in the bright-light example.
Response|A change in an organism’s activity caused by a detected stimulus|A plant shoot bends towards a light source. What is the bending in general biological terms?|Stimulus;Organ;Waste product|The direction of light is the stimulus and bending growth is the response. Plants can respond slowly without walking.|Explain how this observation shows that plants have sensitivity.
Kidneys|Organs that remove urea and excess water from blood to form urine|Which organs form urine rather than merely storing it?|Lungs;Stomach;Heart|Kidneys form urine, whereas the bladder stores it before release. Both contribute to the urinary system but perform different jobs.|Distinguish the roles of the kidneys and bladder.
Carbon dioxide|A gaseous waste of aerobic respiration removed through human lungs|Which respiratory waste gas moves from the blood into the lungs to be breathed out?|Oxygen;Helium;Nitrogen only|Cells produce carbon dioxide; blood carries it to the lungs and breathing removes it. Oxygen is taken in for aerobic respiration rather than being its waste gas.|Describe the route of this waste from cells to the outside air.
Breathing|Movement of air into and out of the lungs|The chest rises and falls as air moves in and out. Which process can be observed?|Cellular respiration;Digestion;Urine formation|Breathing exchanges air. Cellular respiration releases energy chemically; breathing supports it by supplying oxygen and removing carbon dioxide.|Give one difference and one connection between breathing and respiration.
Energy|The resource released from food during respiration that supports life activities|What does respiration supply for movement, growth and repair?|Feathers;Soil;Sunlight directly|Food contains chemical energy. Cells transfer some of this into useful forms to power their activities.|Name two activities needing energy and explain how respiration supports them.''')

add(6,'Science','Classifying plants by root system','B6.1.1.1.1',23,'Compare teacher-provided bean and grass seedlings or clear photographs. Draw the entire root arrangement. Identify a dominant main root or many similar roots; classify with reasons. Replant viable specimens.','Do not uproot protected plants or taste roots. Wash hands after handling soil.', '''Taproot system|A root arrangement with a prominent main root and smaller side roots|A bean seedling has one thick main root with thinner branches. Which root system is it?|Fibrous root system;Flower cluster;Leaf network|The prominent main root is the deciding feature. Side roots branch from it rather than all arising as similar roots at the stem base.|Explain the visible evidence used to classify the bean seedling.
Fibrous root system|A root arrangement with many relatively thin, similarly sized roots near the stem base|Grass has many thin roots without one dominant main root. Which root system is present?|Taproot system;Flowering system;Leaf network|The spreading network grips surface soil. Many roots distribute the anchorage rather than relying on a single main root.|Explain how this root arrangement can help hold soil in place.
Lateral root|A side branch from another root|A thin root branches from a thick central root. What is the thin branch called?|Petal;Leaf blade;Stamen|Side branches spread into more soil and increase the area reached by the root system. Their presence does not prevent the main root from being dominant.|Explain how side roots help a plant reach soil resources.
Root hairs|Tiny root-surface extensions that increase the absorbing area|A magnified root shows many fine hair-like extensions. What are they?|Petals;Seeds;Thorns|These extensions increase contact with water films around soil particles. They are much smaller than the main roots of a fibrous system.|Explain why many of these extensions can improve water uptake.
Absorption|Taking water and dissolved mineral nutrients into a root|A watered seedling takes up water through its roots. Which root function is shown?|Pollination;Seed dispersal;Photosynthesis|Roots take in water and dissolved nutrients rather than swallowing lumps of soil. The plant still makes sugars by photosynthesis.|Explain why roots do not need to take in lumps of soil to obtain minerals.
Anchorage|Holding a plant firmly in the ground|Roots grip the soil and help stop a plant blowing over. Which function is shown?|Pollination;Fruit formation;Seed dispersal|Both major root systems can hold plants in place. A main root and a spread of many smaller roots are different arrangements for support.|Explain how both taproot and fibrous systems can support a plant.
Storage root|A root enlarged to hold stored food|A carrot’s thick underground root contains food reserves. How can it be described?|Flower bud;Leaf stalk;Seed coat|A carrot is a storage root. Not all underground storage organs are roots: a potato tuber is a stem, so position alone does not settle the classification.|Explain why an underground organ is not automatically a root.
Grass|A familiar plant usually showing a fibrous root system|Which plant is a suitable common specimen for a dense cluster of similarly sized roots?|Bean;Carrot;Mango seedling|Its root arrangement is fibrous, with no dominant main root in the usual specimen. Examine the arrangement rather than relying only on a plant name.|State the observations needed to confirm the classification of a grass specimen.
Bean|A familiar seedling that typically develops a taproot system|Which seedling is a suitable taproot comparison with grass?|Maize;Rice;Onion|A young bean commonly shows a main root with side branches. The contrast with a cluster of similar roots should be visible in a labelled drawing.|Describe a drawing that clearly compares bean and grass roots.
Root system|The complete collection and arrangement of a plant’s roots|A pupil draws a main root and all its visible branches. What complete structure is shown?|Single leaf;Flower head;Seed coat|The overall arrangement is needed for classification. A broken fragment may not show whether a main root dominated the original system.|Explain why classification from one broken root may be unreliable.''')

add(7,'Science','States of matter and the importance of liquids','B7.1.1.1.1–2',55,'Compare a stone, water poured between two containers, and air in a balloon. Predict and record shape and volume behaviour. Draw particle models, then link liquid properties with safe daily uses.','Use room-temperature water. Do not taste unknown liquids or heat sealed containers.', '''Solid|A state of matter with definite shape and approximately fixed volume under ordinary conditions|A stone keeps its shape when moved from a bowl to a box. Which state is it in?|Liquid;Gas;Vacuum|Particles are closely arranged and vibrate about relatively fixed positions. This helps the material retain its shape rather than flow like a liquid.|Use a particle explanation for the stone’s fixed shape.
Liquid|A state with approximately fixed volume but the shape of the occupied part of its container|Water changes shape when poured into a wider bowl without spilling. Which state explains this?|Solid;Gas;Vacuum|Particles stay close but can move past neighbours. Shape changes without a large change in the amount of space occupied.|Explain why pouring changes shape but not the volume of the water.
Gas|A state with neither fixed shape nor fixed volume, spreading through available space|Air spreads throughout an inflated balloon. Which state is represented?|Solid;Liquid;Ice|Particles are widely separated and move freely. The material fills available space rather than forming a fixed-volume pool.|Explain how particle arrangement helps this state fill a container.
Volume|The amount of three-dimensional space a substance occupies|A cylinder reading is 100 mL. Which quantity has been measured?|Mass;Temperature;Length|Millilitres and cubic centimetres measure volume. A balance measures mass, which is a different property.|Distinguish volume from mass and name one measuring tool for each.
Flow|Movement of a liquid enabled by particles moving past one another|Water travels through a pipe towards a tap. Which behaviour makes this possible?|Keeping a fixed shape;Having no particles;Always expanding like a gas|Liquid particles can change neighbours while remaining close. This permits movement along a pipe or into another container.|Use particle movement to explain this behaviour.
Compression|Reduction of a substance’s volume by applying pressure|A sealed air-filled syringe can be pushed inward more easily than a water-filled one. Which process is easier for air?|Melting;Freezing;Boiling|Gas particles have much more space between them. Pressure reduces those separations; liquid particles already lie close together.|Explain why trapped air is more compressible than water.
Water|A common liquid essential for human hydration|After exercise, which substance is suitable for replacing lost body water when it is potable?|Kerosene;Petrol;Paint thinner|Safe drinking water replaces losses such as sweat. A clear liquid may still contain harmful substances or organisms.|Explain why clear appearance does not prove a liquid is safe to drink.
Solvent|A substance that dissolves a solute to form a solution|Sugar dissolves in water. What role does the water play?|Undissolved residue;Filter paper;Solid solute|Water dissolves the sugar, but the sugar still exists in the mixture. Individual grains are no longer visible because particles are distributed through the solution.|Explain why dissolved sugar has not ceased to exist.
Lubrication|Use of a suitable material to reduce friction between moving surfaces|A mechanic puts suitable oil between moving parts to reduce rubbing. What use of liquids is shown?|Condensation;Filtration;Freezing|A separating layer reduces direct rubbing and wear. The correct lubricant must be chosen for the equipment.|Explain how a suitable oil can reduce wear on moving parts.
Meniscus|The curved liquid surface in a narrow container|A learner reads the bottom of the water curve at eye level in a cylinder. What feature is being read?|Balance pointer;Thermometer bulb;Ruler edge|Read water at the bottom of its curve with the eye level with the mark. Place the cylinder upright on a level surface to avoid misleading readings.|Describe two steps for accurately measuring water volume.''')

add(8,'Science','Types and characteristics of mixtures','B8.1.1.1.1',62,'Observe labelled samples of salt and water, sand and water, and cooking oil and water. Predict, stir, allow to stand, then record whether each is uniform and whether layers or sediment form. Use observations to justify classifications.','Use small quantities of familiar materials. Do not taste mixtures. Clean spills and wash hands.', '''Mixture|Two or more substances physically combined without forming one new pure substance|Salt is stirred into water without becoming a new compound. What material results?|Element;Single pure compound;Atom|The substances retain their chemical identities, proportions can vary and physical methods can separate them.|Explain two reasons salt water belongs to this category rather than being a pure compound.
Homogeneous mixture|A mixture with uniform composition throughout at the scale considered|Samples from different parts of a well-stirred salt solution have the same concentration. Which type is it?|Heterogeneous mixture;Pure metal;Single element|Dissolved salt is uniformly distributed, but both salt and water remain present. Uniform appearance does not establish purity.|Explain why looking uniform does not mean containing only one substance.
Heterogeneous mixture|A mixture with non-uniform composition and different regions or phases|Sand settles at the bottom of water, leaving different proportions in different regions. Which type is shown?|Homogeneous mixture;Pure substance;Single compound|Visible sand-rich and water-rich regions provide evidence of non-uniformity. This differs from a fully dissolved solute in a solution.|Describe observations supporting this classification of sand and water.
Solute|The substance dissolved in a solvent|In sugar water, which role does the sugar have?|Solvent;Filter paper;Container|Sugar dissolves and is distributed through the water. Water has the dissolving role in this example.|Distinguish the roles of sugar and water in the mixture.
Solvent|The substance that dissolves a solute|A little salt dissolves in a large amount of water. What role does water have?|Solute;Sediment;Residue|The water dissolves salt and forms the continuous liquid phase. In this familiar example it is also present in the larger amount.|Explain the role of water compared with the role of salt.
Solution|A homogeneous mixture of solute distributed in solvent|Salt fully dissolves in water and does not settle on standing. What has formed?|Suspension;Pile of crystals;Pure element|The dissolved particles are too small to be trapped by ordinary filter paper. Removing visible grains is not the same as removing dissolved salt.|Explain why ordinary filtration does not remove dissolved salt from water.
Suspension|A mixture with dispersed particles that may settle and can often be filtered|Muddy water becomes clearer at the top after standing. What type describes the original mixture?|True solution;Pure liquid;Element|Larger soil particles settle under gravity. Fine particles and harmful organisms may remain, so clearer appearance does not ensure safety.|Explain why standing muddy water may become clearer without becoming safe to drink.
Immiscible liquids|Liquids that do not mix into one uniform liquid phase|Cooking oil and water form separate layers after shaking and standing. How are they described?|Miscible liquids;Dissolved solids;Pure gases|Shaking disperses droplets temporarily; it does not turn the pair into a stable uniform solution. Separate phases form again.|Explain why shaking does not permanently remove the distinction between oil and water.
Miscible liquids|Liquids that mix uniformly in all proportions under stated conditions|A teacher shows water mixing uniformly with ethanol. How are the liquids described?|Immiscible liquids;Suspended solids;Sediment|Water and ethanol form a uniform liquid mixture; oil and water form separate phases. Alcohol demonstrations require supervision and no flames.|Contrast these liquids with oil and water.
Air|A familiar mixture of gases, mainly nitrogen and oxygen|Which everyday material disproves the claim that every mixture must be a solid in a liquid?|Pure oxygen;Pure copper;Pure distilled water|Air contains several gases, not one pure gas. Mixtures can combine gases as well as solids or liquids.|Explain why this material is a mixture and name its two major gases.''')

add(4,'Computing','Parts of a computer and their functions','B4.1.1.1.1',54,'Label a switched-off desktop or pictures. Model typing a sentence: input → processing → output → storage. Match keyboard, mouse, monitor, system unit, speakers and storage to their roles.','Do not open computer cases or touch sockets. Use dry hands and keep liquids away.', '''Keyboard|An input device mainly used to enter letters, numbers and commands with keys|Ama wants to type her name in a document. Which device should she use?|Monitor;Speaker;Printer|Pressing keys sends input; the monitor displays the result. Entering text and displaying it are different roles.|Explain the different roles of keyboard and monitor when typing a name.
Mouse|An input device used to move a pointer and select on-screen items|Kojo wants to click a desktop icon. Which device is suitable?|Speaker;Printer;Monitor|Moving the device controls the pointer and clicking selects an item. Holding a button while moving can drag an item instead.|Describe how to select an icon without accidentally dragging it.
Monitor|An output device displaying text and images|A learner wants to see the sentence just typed. Which device shows it?|Keyboard;Mouse;Microphone|The screen presents visual output but does not itself guarantee that the document has been saved to persistent storage.|Explain why seeing a sentence on screen does not mean it is saved.
System unit|The main desktop case containing components such as processor and memory|A teacher points to the main case connected to a desktop monitor. What is it?|Keyboard;Speaker;Mouse|The case houses several components. The CPU is the processor inside, not a precise name for the whole case.|Explain why the whole case and the CPU are not the same thing.
Processor|The component that executes instructions and performs calculations and control operations|A computer carries out an addition instruction. Which component performs this processing?|Monitor;Speaker;Keyboard|It works with memory to execute instructions. A keyboard supplies input and a monitor can display the processed answer.|Describe its role in an input–process–output example.
Speakers|Output devices that convert audio signals into audible sound|A class needs to hear recorded instructions. Which devices provide the sound?|Keyboard;Scanner;Mouse|These devices reproduce sound. A microphone captures sound as input, which is the opposite information direction.|Distinguish these devices from a microphone.
Printer|A device producing physical copies of digital text or pictures|A pupil needs a paper invitation to take home. Which device is required?|Monitor;Keyboard;Microphone|A paper printout is hard copy. The electronic document displayed on screen is soft copy.|Explain the difference between the paper invitation and its on-screen version.
Storage drive|A component retaining saved files for later use, including after power is removed|A saved document is reopened the next day. Which component retained it?|Speaker;Mouse;Keyboard|Persistent storage keeps saved files without continuous power. Unsaved changes in working memory may still be lost.|Explain why work should be saved before shutdown.
RAM|Working memory for data and programs currently in use, normally losing contents without power|Which memory normally loses its current contents when a computer is switched off?|USB flash drive;Hard disk;Printed page|This memory supports current work but does not replace saving to persistent storage. Its ordinary contents are volatile.|Contrast working memory with storage when editing a document.
USB flash drive|A small removable storage device commonly connecting to a USB port|A teacher transfers an approved presentation using a pocket-sized storage device. Which device is it?|Monitor;Mouse pad;Speaker|Use approved devices to reduce malware risk, and follow safe-eject procedures to reduce the chance of losing data.|State two precautions for using removable storage.''')

add(5,'Computing','Output devices and analogue/digital representation','B5.1.1.1.1–3',54,'Match a screen, printout, speakers and projector to classroom tasks. Compare a continuously moving pointer with a numeric display. Distinguish representation from the entire internal design of a device.','Keep audio at a safe volume. Do not touch hot printer parts or remove equipment covers.', '''Output device|Equipment presenting information from a computer to a user|A computer sends a finished picture to a screen. Which device category does the screen belong to?|Input device;Storage medium;Processing unit|The information travels outward to the user. Input travels into the computer instead.|Explain how information direction distinguishes input and output.
Monitor|A device providing visual output on a screen|Which device lets a learner preview a poster without printing it?|Keyboard;Mouse;Scanner|An electronic preview can be corrected before paper is used, reducing unnecessary printing.|Explain how previewing can save paper.
Printer|A device producing a physical copy on paper or another suitable material|A school needs paper copies of a letter for parents. Which device is suitable?|Microphone;Keyboard;Mouse|Check the document and permission to print, then ensure paper and ink or toner are available.|State two checks or resources needed before printing a class set of letters.
Speakers|Devices providing audible output to nearby listeners|The whole class listens to a recorded story. Which devices can play it aloud?|Scanner;Mouse;Keyboard|Clear sound needs suitable placement and volume. Excessive volume can harm hearing or disturb other classes.|Explain two considerations for classroom audio output.
Headphones|Devices providing sound output mainly to the wearer|One learner needs pronunciation practice without disturbing others. Which device is suitable?|Projector;Printer;Scanner|They reduce disturbance but still require a safe volume. A headset may add a microphone, whereas listening alone is output.|Explain why these devices suit independent audio practice.
Projector|A device displaying an enlarged visual image on a screen or wall|A teacher wants the whole class to see a presentation. Which output device is suitable?|Keyboard;Microphone;Mouse|A suitable light-coloured surface and controlled room lighting improve visibility; learners need an unobstructed view.|Describe two arrangements that improve a projected image.
Hard copy|Information in a physically printed form|A pupil holds a printed timetable. Which form of output is it?|Soft copy;Audio signal;Program code only|A printed copy is readable without a screen. A digital copy is easier to update, but requires a suitable device to view.|Compare one advantage of printed and electronic timetables.
Soft copy|Information in electronic form, commonly viewed on a screen|A timetable is opened on a tablet but not printed. Which form is being viewed?|Hard copy;Paper record;Printed photograph|An electronic document can be edited and redistributed without reprinting all copies. Access still depends on an appropriate device.|Explain why this form is useful when a timetable changes.
Analogue representation|A representation varying continuously with the quantity represented|A pointer moves smoothly as a measured value changes. Which representation is illustrated?|Digital representation;Binary file only;Printed code only|Pointer position can vary continuously. This example concerns the displayed representation, not a claim about all internal electronics.|Explain continuous change using the pointer example.
Digital representation|A representation using distinct values or symbols rather than a continuous range of states|A counter shows 101 and then 102 as separate numeric steps. Which representation is illustrated?|Analogue representation;Unmarked liquid level;Continuous dial position|Distinct symbols encode separate values. Digital computers commonly use binary states to encode information.|Contrast the counter with a smoothly moving dial pointer.''')

add(6,'Computing','Computer generations and system components','B6.1.1.1.1–2',51,'Construct a picture timeline: vacuum tubes, transistors, integrated circuits, microprocessors. Sort examples into hardware, software and liveware, then explain how the categories cooperate to create a school document.','Use photographs for internal components. Do not dismantle equipment or handle exposed electrical parts.', '''Hardware|The physical equipment of a computer system|A learner can touch a keyboard and monitor. Which system category contains them?|Software;Liveware;Data only|Physical equipment is tangible. A word-processing program is a set of instructions rather than another physical keyboard.|Distinguish a keyboard from a word-processing program in system classification.
Software|Programs and instructions telling computer hardware what to do|A word-processing application is installed. Which category does it belong to?|Hardware;Liveware;Furniture|Installing a program adds instructions or data to storage, not a new physical input device. Hardware executes those instructions.|Explain why installing a program is not the same as adding a physical device.
Liveware|The people who use, manage or support computer systems|A teacher enters marks and checks the results. Which system category describes the teacher?|Hardware;Software;Storage|People choose tasks, enter accurate data and interpret output. The system does not remove human responsibility for mistakes.|Explain one responsibility of a user in producing accurate results.
Input device|Equipment sending data or instructions into a computer|A scanner captures a drawing for a computer. Which role is it performing?|Output device;Storage only;Liveware|It sends a digital representation inward. The image may then be processed, displayed and saved.|Trace a scanned drawing through input, processing and output.
Output device|Equipment presenting information from a computer|A completed graph is displayed to the class. Which device role presents the result?|Input device;Processor;Liveware|A monitor or projector presents visual output; a printer can present the same graph as hard copy.|Name two output forms for the graph and suitable devices.
Storage|Keeping files and programs for future use|Pupil records must be reopened next term. Which system function is required?|Audio output only;Pointing;Scanning only|Saving retains the working file; a separate backup supports recovery if that copy is lost. Sensitive records also need access controls.|Explain the difference between saving and backing up school records.
Vacuum tubes|Electronic components associated with first-generation computers|A museum describes an early electronic computer built with tubes that used substantial space and power. Which technology is described?|Microprocessors;Transistors only;Integrated circuits|Many early computers using this technology were large, produced substantial heat and required more power than later transistor designs.|Explain two practical disadvantages compared with later designs.
Transistors|Electronic components associated with the second generation, replacing many tube functions|A timeline shows smaller switching components replacing vacuum tubes. Which technology marks the change?|Mechanical abacus only;Microprocessors only;Quantum bits only|These components were smaller and generally used less power than tubes, supporting improved size and reliability.|Explain why this replacement was important.
Integrated circuits|Many electronic components combined on a small chip, associated with the third generation|A timeline moves from separate transistors to many components on one chip. Which technology follows?|Paper tape alone;Vacuum tubes;Mechanical gears|Combining components reduces space and supports more complex circuits. A microprocessor is a particular highly integrated processor, not every circuit chip.|Explain how combining components on chips can reduce computer size.
Microprocessor|A processor implementing CPU functions on an integrated-circuit chip|A timeline links personal computers with CPU-on-a-chip technology. What is it?|Vacuum tube;Paper card;Mechanical relay|Integration helped make smaller, affordable general-purpose systems possible. Modern devices still differ in power and purpose.|Explain how this technology helped personal computers develop.''')

add(7,'Computing','Fourth-generation computers and input devices','B7.1.1.1.1–2',15,'Link microprocessors with the development of personal computers. Match product codes, paper images, speech and typed reports to appropriate input devices. Demonstrate only teacher-approved codes and files.','Do not scan unknown links or use private learner data. Obtain permission before recording anyone.', '''Microprocessor|A CPU implemented on a chip, central to fourth-generation development|A small computer processes instructions using a CPU on a chip. Which technology is involved?|Vacuum tubes;Mechanical gears;Punched cards alone|A compact integrated processor is not merely a smaller monitor. It helped make smaller, affordable computer systems practical.|Explain how this technology contributed to personal computers.
Personal computer|A general-purpose computer designed mainly for an individual user|A learner uses a laptop for documents, calculations and learning. Which broad category fits?|Supercomputer only;Mechanical calculator only;Network cable|Both laptops and desktops can support one user’s general tasks. The physical shape alone does not define the category.|Explain why a desktop and laptop can share this classification.
Input|Data or instructions supplied to a computer|A cashier enters a product code before a total is calculated. Which processing stage is this?|Output;Backup only;Display|The code enters as input; software looks up the product and calculates a total; the screen or receipt presents output.|Describe input, processing and output in a checkout example.
Barcode reader|A device reading an encoded pattern of bars or a supported product code|A cashier scans stripes on a packaged item. Which input device is used?|Speaker;Printer;Projector|The code is often an identifier used to retrieve the price from a database. It need not contain the price itself.|Explain why changing a price may not require changing a barcode.
Scanner|A device capturing a paper document or picture as a digital image|A school wants a digital image of an old printed photograph. Which device is suitable?|Speaker;Projector;Printer only|Scanning captures an image. Recognising printed characters as editable text requires an additional process such as OCR.|Explain why scanning a page does not automatically make its words editable.
OCR|Recognition of printed characters in an image as machine-readable text|A teacher wants to edit text from a scanned letter without retyping it all. Which process can help?|Audio playback;Paper printing;Screen projection|Recognition can confuse similar characters, especially in poor-quality scans. Proofreading is needed to correct mistakes.|Explain why the converted text should be proofread.
Microphone|A device capturing sound as input|A learner records a spoken explanation. Which device provides the audio input?|Speaker;Monitor;Printer|It captures sound, whereas speakers reproduce sound. Recording other people also requires attention to consent and privacy.|Explain the input/output difference between this device and speakers.
Keyboard|A keyed input device for entering text and commands|A pupil is composing an entirely new long report. Which device best suits entering the text?|Monitor;Projector;Speaker|Typing creates new text from the learner’s ideas. Scanning instead captures an existing page or picture.|Explain why typing is more suitable than scanning for an entirely new report.
Touchscreen|A device combining visual display with sensing of touch input|A learner sees a menu and selects by touching that same screen. Which device is used?|Ordinary speaker;Paper printout;Non-touch monitor|The display presents output while the touch sensor receives input. One physical device may perform more than one role.|Explain why classifying this device only as output is incomplete.
Data validation|Checking input against rules such as permitted types or ranges|A form rejects an age of 250 for a primary-school pupil. Which check is applied?|Printing;Screen projection;Audio output|A range rule rejects implausible data. A plausible but wrong age may pass, so validation cannot guarantee truth.|Explain why valid data may still be inaccurate.''')

add(8,'Computing','Fifth-generation themes, AI and quantum computing','B8.1.1.1.1',21,'Compare ordinary computers, AI applications and introductory quantum computing. Discuss speech recognition and image classification. Model a classical bit with two labelled cards but explain that coin-toss randomness is not a complete model of a qubit. Evaluate exaggerated claims about new technology.','Use fictional data. Do not create learner accounts or upload private records or recordings for demonstrations.', '''Artificial intelligence|Computational methods for tasks associated with learning, reasoning or perception|A program identifies likely objects in photographs using learned patterns. Which field is illustrated?|Paper storage;Mechanical printing only;Manual filing|Such systems may make mistakes and depend on design and training data. Their output does not imply reliable human-like understanding of every situation.|Explain why an answer produced by such a system should be checked.
Natural language processing|Computational work with human language|A system analyses a typed question and produces a language-based response. Which area is involved?|Disk formatting;Screen cleaning;Paper binding|Language applications include translation or question answering. Ambiguity and unfamiliar usage may cause errors.|Give one useful application and one reason its output needs checking.
Machine learning|Using examples and data to fit models that identify patterns for predictions or decisions|A spam filter is trained on labelled spam and non-spam messages. Which approach is used?|Manual sorting only;Paper printing;File copying only|The examples influence the learned patterns. Biased or unrepresentative training data can produce poor decisions.|Explain how unsuitable training examples affect a spam filter.
Robotics|The study and use of machines that sense and act in the physical world under control or programming|A moving machine uses sensors to avoid obstacles. Which field best describes this?|Word formatting only;Paper filing;Audio playback only|A robot has physical sensing and action. Not every robot uses AI and not every AI system is a physical robot.|Distinguish a robot from an AI text program.
Bit|A classical information unit with one of two logical values, commonly 0 or 1|A stored switch state is represented as either 0 or 1. Which information unit is this?|Qubit superposition;Paragraph;Printed page|One such unit has two states; groups of units encode many patterns for numbers, letters and other information.|Explain how units with only two states can encode more complex information.
Qubit|A unit of quantum information described by a quantum state|A researcher manipulates the information units of a quantum processor. What are these units called?|Printed character;Mechanical gear;Ordinary byte only|This is not simply a faster ordinary bit. Its state can involve superposition, while a computational-basis measurement produces 0 or 1.|Explain one difference between this unit and a classical bit.
Superposition|A quantum state formed as a combination of basis states before measurement|A lesson describes a qubit state as a combination of the 0 and 1 basis states. Which concept is intended?|Ordinary file duplication;Paper copying;Classical certainty only|This does not let a user read every possible classical answer at once. Measurement gives an outcome with probabilities determined by the quantum state.|Explain why this concept does not mean all answers can simply be read at once.
Measurement|An operation producing a classical outcome from a quantum observation in a chosen basis|A scientist reads a qubit in the computational basis and records 0. What operation occurred?|Document formatting;Paper scanning;Keyboard printing|One such observation gives a single classical outcome. Repeated experiments can estimate probabilities rather than revealing every outcome from one run.|Explain why repeated runs can help interpret a quantum experiment.
Quantum computing|Information processing using quantum states and operations, potentially advantageous for selected specialised problems|A team investigates algorithms implemented using qubits. Which approach is being studied?|Manual arithmetic only;Ordinary paper filing;Mechanical typewriting|This is not faster for every task, and practical systems face noise and engineering limits. Ordinary computers remain appropriate for everyday documents.|Explain why this approach is not automatically the best tool for typing a school letter.
Human oversight|People checking, guiding and taking responsibility for automated systems|A teacher checks an AI explanation against trusted sources before teaching it. Which practice is shown?|Blind trust;Automatic copying;Ignoring evidence|People should verify facts, consider bias and protect privacy. Output is something to evaluate, not an unquestionable authority.|State two checks a teacher should make before using an AI-produced resource.''')
